### ISSUE TITLE
Sound resets to max on launch

### ISSUE THREAD

**Issue by reficulagi** [jadedcat/MF3Configs#1]
When ever I relaunch MF3 on 1.1.34 the sound goes back to default. I look in the options and it shows that i have the sound set to 20% on all settings. the sounds will go back to what i have them set at as soon as i readjust the volume again.

**Comment by Infernalized** [comment]
This sounds more like a vanilla issue but try this:
Go into your instance folder and open the options with notepad or like and see what soundCategory_*(master,music etc.) are set at. And setting them in the file might fix it.

**Comment by reficulagi** [comment]
The soundCategory_ are at the values that are set in game. I have not had this happen on older versions nor has it happened on different mod-packs that I play.

**Comment by Infernalized** [comment]
I'm not sure then, I know that this has happened to me in the past. However I never actually found out how to fix it other then a clean install.

**Comment by Infernalized** [comment]
Can confirm this issue and have no solution for it atm.

**Comment by jadedcat** [comment]
o.0

**Comment by shadowfacts** [comment]
@reficulagi Can you please provide a paste of the log? MC might be having a problem writing to the options file.

**Comment by Solaxi** [comment]
Happens with Agrarian Skies 2 as well, but not with Anti-Material Energy for instance.

**Comment by reficulagi** [comment]
@Shadowfacts here is a pastbin of the lasest log http://pastebin.com/95XE8PvL

**Comment by Hlexyn** [comment]
@jadedcat Had the same problem with AS2. Fixed by disabling the Origin mod. I noticed in the config a bunch of sound settings to fiddle with if you wanted to keep Thaumic Expansion (which depends on Origin).

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#14
