### ISSUE TITLE
MF3: Axe of the stream doesn't work on thaumcraft trees

### ISSUE THREAD

**Issue by Monsterbee** [jadedcat/MF3Configs#10]
Axe of the stream isn't upgradable in any way to work on greatwood trees- which was their intended purpose. Is this going to be rectified at some point? This is highly inconvinient and makes thaumcraft tools outdated, which is strange given how late in progression infusion generall happens.

**Comment by ghost** [comment]
If this is considered, the axe of the stream would need to be set to a higher woodcutting level. Leaving for jaded devs to investigate if this is intended behavior.

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#5
