### ISSUE TITLE
Magic Farm 3 Harvest Server Crash

### ISSUE THREAD

**Issue by Dreadwhelp** [jadedcat/MF3Configs#12]
Hey guys, not entirely sure what is causing this crash but it only ever happens when I or my friend travel to a mystcraft dimension, rarely it does not crash but it can be as frequent as every couple of minutes where the server is forced to stop and in my server cmd the last message is 'The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOP. Errors my have been discarded.' 
And this is the crash report <script src="http://pastebin.com/embed_js.php?i=AP8h89FU"></script>

**Comment by dmf444** [comment]
Please post the crash report

**Comment by ghost** [comment]
No update from user with no crash report supplied. Closing. If user posts crash report, this issue may be re-opened.
