### ISSUE TITLE
MF3 Crash Report Unknown Reason

### ISSUE THREAD

**Issue by iHibariKyoya** [jadedcat/MF3Configs#14]
I have no idea what is causing this. I was in for a minute or two and after dealing with the start up lag (which is normal as I've come to find on my laptop) it simply crashes. This is the fourth time and everything is the same in the reports (I have no idea what the stuff means but it's all the same).

http://pastebin.com/cUSVcyt1 This link is my crash report log thing.

Bit more info, this has only seemed to happen as I started breeding plants toward the Redstone plant seed. Not very sure how much this might help but if it does even a small bit I'm content to have posted this.

**Comment by westloar** [comment]
I have this very same issue. However I may be able to shed some more light on it.

I only started getting this crash after the update on curse to 1.1.34 on 10/10/15, although I recently just started using agricraft in my world, the fact you were able to almost redstone suggests that it is more likely to be related to the update.

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#6
