### ISSUE TITLE
Nether Ore generation

### ISSUE THREAD

**Issue by garlicinyoureye** [jadedcat/MF3Configs#16]
This may be what you intended but Redstone, Silver, Lead, Gold ores and Lapis do not generate in the nether.  The only ores I have been able to find are Diamond, Emerald, Coal, Iron, Tin, Copper, Salt, Saltpeter and Sulfur, nether quartz.

**Comment by ghost** [comment]
Certain high level ores are disabled (see https://github.com/jadedcat/MF3Configs/blob/master/config/powercrystals/netherores/common.cfg)

However, the ones you mentioned /should/ spawn, maybe you're just unlucky with finding them.
