### ISSUE TITLE
Agricraft water tanks & Cauldrons don't fill with water

### ISSUE THREAD

**Issue by LMShocklogic** [jadedcat/MF3Configs#19]
The birch water tank (not tested with other wood types) when being filled with a bucket empties the bucket but does not take the water (No water visually in tank and volume in WAILA is 0/8000). Worked before the most recent update, but since updating won't fill. I've tried taking down and replacing the block, but no luck.

**Comment by Aravenqueen** [comment]
it does this with similar objects like cauldrons too now

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#3

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#7
