### ISSUE TITLE
Black screen on start up 

### ISSUE THREAD

**Issue by Netherguy** [jadedcat/MF3Configs#2]
blak screen on start up but the I hear the minecraft music and can click on the menu but all i see is white screen here is my log http://pastebin.com/h6cxwB5t

**Comment by MarshMilo100** [comment]
You did not give the correct log, this is corrupted or is not even the right file.

**Comment by Netherguy** [comment]
What should the file look like

**Comment by MarshMilo100** [comment]
It should be in English

**Comment by MarshMilo100** [comment]
It is called fml-client-latest.log
