### ISSUE TITLE
Hqm Issues

### ISSUE THREAD

**Issue by gravestristen** [jadedcat/MF3Configs#20]
I finished everything so far but the other tabs are locked and I don't know how to open them!

![screen shot 2015-11-02 at 12 23 02 am](https://cloud.githubusercontent.com/assets/7584667/10874838/a36d5c96-80f8-11e5-8707-a04ba2f329cf.png)

**Comment by ghost** [comment]
There are some "hidden" quests, that require you to craft secret items. Sadly, we can't say which as it'll spoil the game, but make sure you crafted all the progressive stuff that would have lead you up to the higher quests ;)
