### ISSUE TITLE
Enderium Mining Level

### ISSUE THREAD

**Issue by gamorex** [jadedcat/MF3Configs#27]
According to [this page](http://jadedpacks.gamepedia.com/Tinker_Materials), enderium should have the same mining level of obsidian. This seems to match in game, version 1.1.34, but the tool tip says mining level manyullyn.

![enderium_1](https://cloud.githubusercontent.com/assets/16447345/12007958/c20f01cc-abeb-11e5-8026-a36096fb7a50.png)
![enderium_2](https://cloud.githubusercontent.com/assets/16447345/12007959/c2102ebc-abeb-11e5-99c1-1da5863445ed.png)

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#8
