### ISSUE TITLE
MF3HQM not working

### ISSUE THREAD

**Issue by MgDeception** [jadedcat/MF3Configs#29]
When I download the mod it says it is a HQM based game but when you spawn in the world you don't get a quest book and you can not make one either. Is that a bug or is the mod not an HQM modpack?

**Comment by belnumcree** [comment]
HQM was removed

**Comment by MgDeception** [comment]
For good then?

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#12
