### ISSUE TITLE
Vein Miner - hatchet is not working

### ISSUE THREAD

**Issue by lasiecz** [jadedcat/MF3Configs#3]
Hey there,

I started to play MF3 but the Vein Miner is not working with hatchet from TiCo. Do I have to set it somehow in config file or it is not working? I am using the GRAVE key and nothing happedn.

TY much

**Comment by pjfranke** [comment]
The config is set to use no_key to activate veinminer, which means it should be active be default.  It is also set to use the TiC hatchet.  Have you tried without holding a keys?  Does it only break one block, and at normal speed?

**Comment by lasiecz** [comment]
I tried with key, without and sneaking but nothig of it works. Yes, just one block normal speed nothig special. Its flint hatchet. Maybe some bug.

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#9
