### ISSUE TITLE
Magic Farm 3 - Search Crash

### ISSUE THREAD

**Issue by IrishRaven** [jadedcat/MF3Configs#32]
Hey, having a little issue and not sure where to go for help so I'd love to have your input on a fix or where I should go to maybe find one.

So I recently started a SP Magic Farm 3 and all runs perfect minus one little issue.. searching, using the Minecraft search bar, NEI search bar, or even trying to look up a recipe though NEI causes me to crash.

Here's my report, any insight would be amazing.

[Crash Report Magic Farm 3.txt](https://github.com/jadedcat/MF3Configs/files/252095/Crash.Report.Magic.Farm.3.txt)

Thank you in advance.

**Comment by ryutoshirazen** [comment]
This has already been solved.
I had the same problem but fixed it. I'm using the curse client.
Steps:
If you are using curse client you will need to unlock the profile.
1. Update CodeChickenCore to version 1.7.10-1.0.7.47-universal.jar
2. Update NotEnoughitems to version 1.7.10-1.0.5.118-universal.jar
3. Update NEI integration to version MC1.7.10-1.1.2.jar
4. Update NEI Addons to version 1.12.14.40-mc1.7.10.jar

**Comment by ghost** [comment]
Updating of NEI Integrations will fix the issue. Marking for jaded devs to look at it next round of update.

**Comment by Rev-C** [comment]
I have the same thing except I can search things in NEI but I can't click on any recipes. http://pastebin.com/gWR2EYai <- my crash report

**Comment by ghost** [comment]
@Rev-C Did you update NEI Integrations? >.>

**Comment by Rev-C** [comment]
A. unsure how to do that in the curse client B. switched to previous ver anyway so I can SMP with my friends.

**Comment by BLAMM67** [comment]
Had the same problem. Can confirm updating the mods listed above did the trick. Thanks.

**Comment by gellegbs** [comment]
@Rev-C I know it's kind of late, but to update a mod in a pack or add one in Curse you need to:
1. Click the logo of the mod pack in your Curse Minecraft window.
2. You should be brought to a new tab that says Current Profile Magic Farm 3 (or whatever pack title you are using) on the upper right hand side. Make sure you are in the right place.
3. [Optional- if you don't know the version you want to update to or want to check if the mod is installed] There also should be a tab under the mod pack logo named Installed Mods, click that to show the mod list and look for the mod to make sure it's installed. Once you find the mod you can double click on it to bring you to the mod's page in Curse and click the versions tab to see what version you have installed. Look on list for what version you want to install. Take note of the mod name and version. Hit the back button to go back to the Current Profile page.
4. Use your browser to find the mod with the correct version and download it.
5. Back in your Curse Current Profile page look for the ellipses (...) button on the top right corner. Click that and select _open folder_ from drop down menu.
6. Go to mods folder and drag the downloaded mod into the folder. Delete any old versions of mod. 
7. Close the folder and any instance of the mod pack you may have open.
8. Go back to the main modpack menu and start the pack as normal. If you want to make double sure the mod was properly installed repeat #3 and check the mod list.

**Comment by ghost** [comment]
This issue was moved to JadedPacks/MF3Configs#13
