### ISSUE TITLE
Crashing when trying to see a recipe

### ISSUE THREAD

**Issue by Redhandjane** [jadedcat/MF3Configs#41]
I'm playing version 1.1.36, downloaded through Curse/Twitch. If I try to click an item to see the recipe, I crash. If I enter a map that I already created (like after a crash) I get a fatal error and get kicked out to the multiplayer screen, which is super weird because I'm playing single player. After I get kicked out, I can go back into my map as normal until I crash from trying to see the recipe for something, like Tinker's Construct tables. 

https://pastebin.com/ejk8nqN1

**Comment by AetheriumAeon** [comment]
I am getting the same error and crash situation. Downloaded through Curse/Twitch as well, version 1.1.36.
https://pastebin.com/duhXdsZB

**Comment by ghost** [comment]
This ticket has been relocated to here: https://github.com/JadedPacks/MF3Configs/issues/15
