### ISSUE TITLE
Crash on Opening Recipe Book

### ISSUE THREAD

**Issue by RJKoubaka** [jadedcat/MF3Configs#43]
Hey guys. Made a personal pack with the mod, and it crashes when I open the Recipe Book 1. pastebin is here: https://pastebin.com/STJrUBuN

**Comment by tecrogue** [comment]
I think you may be a bit confused, this mod was for v.1.7.10 of minecraft, and your instance there is running 1.12.2

Also looking through the crashlog, I am not sure which mod's github you were looking to submit this bug report to, but it looks like you found the wrong one accidently.
