### ISSUE TITLE
Eating motion is slow

### ISSUE THREAD

**Issue by ItsKryi** [jadedcat/MF3Configs#5]
I'm not sure if its a bug or if its a part of the mod pack, but I can't find any information on it anywhere. 

When I go to eat the food moves REALLY slow towards my mouth, as if mining fatigue is effecting my eating too. 

I held my right clicker down for almost a minute and I still hadn't eaten the darn fruit. I didn't have any mining fatigue or ailments that show up on the side when you open inventory.

**Comment by jwhite135** [comment]
If you have eaten this food many many times, it diminishes in nutritional value.  It takes longer to eat every time, and gives less hunger.  That is most likely why you are eating slow (unless I'm dumb).

**Comment by ghost** [comment]
@ItsKryi Could you confirm if it's fixed, or still buggy?
