### ISSUE TITLE
Entering Nether (dimensional travel in general?) bugs Sorting chests

### ISSUE THREAD

**Issue by Screwmyshoe** [jadedcat/MF3Configs#6]
I don't know why exactly, but after coming out of the nether my sorting chests and barrels stop working, the dumping chest simply doesn't sort the items into the barrels anymore. It is slightly annoying since the only way of fixing this that i can see is re-entering the world save. Just thought it would be worth to mention.

**Comment by ghost** [comment]
This is due to the fact that the chunks would have been unloaded. Consider chunk loading your base :)
