### ISSUE TITLE
Wood logs, different Charcoal amts

### ISSUE THREAD

**Issue by garlicinyoureye** [jadedcat/MF3Configs#7]
I've noticed that when smelting/cooking Spruce logs and Birch logs.  I don't think this is normal because it's inconsistent, it varies whenever I log/relog the game.  Usually, it's 1,3 or 4 pieces of charcoal per log.  This also happens for the redwood (not the bark or root).  There may be others but those are the only 3 I've had experience with, the Oak logs smelt as normal.  This may be a Steve's workshop thing too, I can't remember if I've seen this happen in the vanilla furnaces but definitely have seen in when smelting in the worktable.

**Comment by ghost** [comment]
I believe this is a jaded tweaks system that changes how much charcoal you get from logs :)
