### ISSUE TITLE
Problem when trying to break blocks

### ISSUE THREAD

**Issue by RedReign** [jadedcat/MF3Configs#9]
My friend's been having a problem on the server he hosts. I'm fine, but whenever he tries to click a block, he freezes and crashes... Seems to have something to do with Tinker's Construct?

http://pastebin.com/N2txZWjP Here's the crash report
http://pastebin.com/aBpt7Nqs and here's the log!

**Comment by BrzlMan** [comment]
Hi, I'm friend.

In addition, if I try to open up my inventory, my client crashes again. 

http://pastebin.com/ePJ9hCQF Here's the crash report...
http://pastebin.com/PpNp1jQY Here's the logs.

Also, the sleep bar on my client was non functioning.
The animals are non violent. (which is a good thing if you don't want to die. I do though.)

Do you need any more info?

UPDATE: I have tried downgrading to 1.1.32, but the same issues occur.

**Comment by ghost** [comment]
Hi @RedReign / @BrzlMan Try updating to the latest version to see if this works better now? I believe tinkers construct has updated during this which should fix this issue.

**Comment by ghost** [comment]
No response, issue being closed. Please re-open if it's still occurring.
